
export const books=[
	{ id: '1', title: 'The Great Gatsby', authorId: '1' },
	{ id: '2', title: 'To Kill a Mockingbird', authorId: '2' },
	{ id: '3', title: '1984', authorId: '3' },
	{ id: '4', title: 'Pride and Prejudice', authorId: '4' },
	{ id: '5', title: 'Animal Farm', authorId: '3' },
	{ id: '6', title: 'Brave New World', authorId: '3' },
	{ id: '7', title: 'Lord of the Flies', authorId: '11' },
	{ id: '8', title: 'The Catcher in the Rye', authorId: '6' },
	{ id: '9', title: 'The Bell Jar', authorId: '12' },
	{ id: '10', title: 'The Picture of Dorian Gray', authorId: '10' },
	{ id: '11', title: 'The Count of Monte Cristo', authorId: '13' },
	{ id: '12', title: 'Crime and Punishment', authorId: '14' },
	{ id: '13', title: 'Anna Karenina', authorId: '15' },
	{ id: '14', title: 'War and Peace', authorId: '15' },
	{ id: '15', title: 'The Brothers Karamazov', authorId: '16' },
	{ id: '16', title: 'The Trial', authorId: '3' },
	{ id: '17', title: 'Heart of Darkness', authorId: '17' },
	{ id: '18', title: 'The Stranger', authorId: '18' },
	{ id: '19', title: 'Nineteen Eighty-Four', authorId: '3' },
	{ id: '20', title: 'Fahrenheit 451', authorId: '19' },
	{ id: '21', title: 'One Hundred Years of Solitude', authorId: '7' },
	{ id: '22', title: 'Love in the Time of Cholera', authorId: '7' },
	{ id: '23', title: 'The Metamorphosis', authorId: '16' },
	{ id: '24', title: 'Life of Pi', authorId: '20' },
	{ id: '25', title: 'The Alchemist', authorId: '21' },
	{ id: '26', title: 'The Hobbit', authorId: '22' },
	{ id: '27', title: 'The Lord of the Rings', authorId: '22' },
	{ id: '28', title: 'The Hitchhiker\'s Guide to the Galaxy', authorId: '23' },
	{ id: '29', title: 'The Chronicles of Narnia', authorId: '24' },
	{ id: '30', title: 'Harry Potter and the Philosopher\'s Stone', authorId: '25' },
	{ id: '31', title: 'Harry Potter and the Chamber of Secrets', authorId: '25' },
	{ id: '32', title: 'Harry Potter and the Prisoner of Azkaban', authorId: '25' },
	{ id: '33', title: 'Harry Potter and the Goblet of Fire', authorId: '25' },
	{ id: '34', title: 'Harry Potter and the Order of Phoenix', authorId: '25' },
	{ id: '35', title: 'Harry Potter and the Half-Blood Prince', authorId: '25' },
	{ id: '36', title: 'Harry Potter and the Deathly Hallows', authorId: '25' },
	{ id: '37', title: 'The Hunger Games', authorId: '26' },
	{ id: '38', title: 'Catching Fire', authorId: '26' },
	{ id: '39', title: 'Mockingjay', authorId: '26' },
	{ id: '40', title: 'Divergent', authorId: '27' },
	{ id: '41', title: 'Insurgent', authorId: '27' },
	{ id: '42', title: 'Allegiant', authorId: '27' },
	{ id: '43', title: 'The Fault in Our Stars', authorId: '28' },
	{ id: '44', title: 'Paper Towns', authorId: '28' },
	{ id: '45', title: 'Looking for Alaska', authorId: '28' },
	{ id: '46', title: 'Me Before You', authorId: '29' },
	{ id: '47', title: 'The Girl on the Train', authorId: '30' },
	{ id: '48', title: 'Gone Girl', authorId: '31' },
	{ id: '49', title: 'The Da Vinci Code', authorId: '32' },
	{ id: '50', title: 'Angels and Demons', authorId: '32' },
	{ id: '51', title: 'The Help', authorId: '33' },
	{ id: '52', title: 'Water for Elephants', authorId: '34' },
	{ id: '53', title: 'The Five People You Meet in Heaven', authorId: '35' },
	{ id: '54', title: 'Tuesdays with Morrie', authorId: '35' },
	{ id: '55', title: 'The Shack', authorId: '36' },
	{ id: '56', title: 'The Lion, the Witch and the Wardrobe', authorId: '24' },
	{ id: '57', title: 'The Horse and His Boy', authorId: '24' },
	{ id: '58', title: 'Prince Caspian', authorId: '24' },
	{ id: '59', title: 'The Voyage of the Dawn Treader', authorId: '24' },
	{ id: '60', title: 'The Silver Chair', authorId: '24' },
	{ id: '61', title: 'The Last Battle', authorId: '24' },
	{ id: '62', title: 'The Kite Runner' }
]

export const authors = [
  { id: "1", name: "F. Scott Fitzgerald" },
  { id: "2", name: "Harper Lee" },
  { id: "3", name: "George Orwell" },
  { id: "4", name: "Jane Austen" },
  { id: "5", name: "Ernest Hemingway" },
  { id: "6", name: "Virginia Woolf" },
  { id: "7", name: "William Shakespeare" },
  { id: "8", name: "J.R.R. Tolkien" },
  { id: "9", name: "Emily Bronte" },
  { id: "10", name: "Charlotte Bronte" },
  { id: "11", name: "Edgar Allan Poe" },
  { id: "12", name: "Leo Tolstoy" },
  { id: "13", name: "Mark Twain" },
  { id: "14", name: "Gabriel Garcia Marquez" },
  { id: "15", name: "John Steinbeck" },
  { id: "16", name: "Mary Shelley" },
  { id: "17", name: "Victor Hugo" },
  { id: "18", name: "Agatha Christie" },
  { id: "19", name: "Charles Dickens" },
  { id: "20", name: "Oscar Wilde" },
  { id: "21", name: "Jane Austen" },
  { id: "22", name: "J.K. Rowling" },
  { id: "23", name: "Stephen King" },
  { id: "24", name: "Ayn Rand" },
  { id: "25", name: "Franz Kafka" },
  { id: "26", name: "Herman Melville" },
  { id: "27", name: "Jack Kerouac" },
  { id: "28", name: "Margaret Atwood" },
  { id: "29", name: "James Joyce" },
  { id: "30", name: "Virginia Woolf" },
  { id: "31", name: "H.G. Wells" },
  { id: "32", name: "Nathaniel Hawthorne" },
  { id: "33", name: "Toni Morrison" },
  { id: "34", name: "Walt Whitman" },
  { id: "35", name: "George Eliot" },
  { id: "36", name: "Joseph Conrad" },
  { id: "37", name: "Gustave Flaubert" },
  { id: "38", name: "J.D. Salinger" },
  { id: "39", name: "Fyodor Dostoyevsky" },
  { id: "40", name: "Albert Camus" },
  { id: "41", name: "Chinua Achebe" },
  { id: "42", name: "Jorge Luis Borges" },
  { id: "43", name: "Isabel Allende" },
  { id: "44", name: "John Milton" },
  { id: "45", name: "Ralph Waldo Emerson" },
  { id: "46", name: "Henry David Thoreau"},
  { id: "47", name: "Maya Angelou 47" },
  { id: "48", name: "Maya Angelou 48" },
  { id: "49", name: "Maya Angelou 49" },
  { id: "50", name: "Maya Angelou 50" },
  { id: "51", name: "Maya Angelou 51" },
  { id: "52", name: "Maya Angelou 52" },
  { id: "53", name: "Maya Angelou 53" },
  { id: "54", name: "Maya Angelou 54" },
  { id: "55", name: "Maya Angelou 55" },
  { id: "56", name: "Maya Angelou 56" },
  { id: "57", name: "Maya Angelou 57" },
  { id: "58", name: "Maya Angelou 58" },
  { id: "59", name: "Maya Angelou59" },
  { id: "60", name: "Maya Angelou61" },
  { id: "61", name: "Maya Angelou 61" },
  { id: "62", name: "Maya Angelou 62" },
];
